### ISSUE TITLE
how to assign?

### ISSUE THREAD

**Issue by sbrinkmeyer** [githubteacher/github-for-developers-sept-2015#115]
sorry i was watching my fingers...
@saranicole how'd you do that?

**Comment by saranicole** [comment]
If you're logged in there's an Assign button on the right above the Notifications button

**Comment by saranicole** [comment]
Click the gear

**Comment by saranicole** [comment]
It's not obviously a button

**Comment by PinoEire** [comment]
:)

**Comment by sbrinkmeyer** [comment]
i'm logged in, but i'm apparently not part of the peoples that get gears ... none of my items are geared :), i wasn't a co lab er tator, thanks @saranicole

**Comment by nathanv** [comment]
@sbrinkmeyer you must not be a collaborator yet. Comment on #1 and ping @jaw6  you will get permissions.

**Comment by patrickmckenna** [comment]
Thanks for the assist, @nathanv!
