### ISSUE TITLE
Webcast Screen View is cut off!

### ISSUE THREAD

**Issue by jmarlena** [githubteacher/github-for-developers-sept-2015#118]
@githubteacher Can't see what you're doing well!
<img width="840" alt="screen shot 2015-09-29 at 9 23 10 am" src="https://cloud.githubusercontent.com/assets/6732600/10170832/bc51de9e-668b-11e5-8cbf-bda5a11e4bf8.png">

Is it like this for others?

**Comment by jaw6** [comment]
@jmarlena looks like you're at 100% Zoom, and @patrickmckenna's screen is a little too large for your display. You can zoom out to see the whole screen: click on the zoom button and select 'Scale to fit'

<img width="175" alt="screen shot 2015-09-29 at 11 25 41 am" src="https://cloud.githubusercontent.com/assets/2077/10170932/f1e30a4a-669c-11e5-87e1-6c3c7dcd9a11.png">

**Comment by jmarlena** [comment]
Thanks!
