### ISSUE TITLE
How to remove a old issues?

### ISSUE THREAD

**Issue by phongta** [githubteacher/github-for-developers-sept-2015#148]

**Comment by saranicole** [comment]
I would click:
`Close issue`

**Comment by phongta** [comment]
Thanks. Found it.

**Comment by jaw6** [comment]
Exactly right: we typically don't delete issues, we use Closed to signify issues that are no longer an active concern, and additionally use labels to help explain. (For example, in a software project, we might use labels like `wont-fix` and `duplicate` to help explain why a particular issue has been closed.)

**Comment by saranicole** [comment]
Awesome
