### ISSUE TITLE
Tá an lá go brea in Eirinn

### ISSUE THREAD

**Issue by ghost** [githubteacher/github-for-developers-sept-2015#151]
An bhfuil Gaeilge ag aon duine?

**Comment by saranicole** [comment]
Níl ach ní mór dúinn Google aistriú a chabhraíonn

**Comment by PinoEire** [comment]
Creidim go bhfuil náid:)

**Comment by saranicole** [comment]
Ár caillteanas ní mise  ;)

**Comment by ghost** [comment]
Tá google translate daimsearach/dangerous :+1:

**Comment by indijanc** [comment]
Wat?

**Comment by saranicole** [comment]
@indijanc https://translate.google.com/#ga/en/T%C3%A1%20an%20l%C3%A1%20go%20brea%20in%20Eirinn
