### ISSUE TITLE
Best Practices for Branch Management in GIT

### ISSUE THREAD

**Issue by jcbustamante2015** [githubteacher/github-for-developers-sept-2015#153]
@githubteacher - Do you have a link of best practices of the Do's and Don'ts of how we should be using branches in GIT? One of the most difficult things in my experience is having a killer branching strategy for managing code (ie having a Master for Releases, and a Development branch for managing changes from feature sets and bug fixes). I would like to know what your thoughts are.

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by jns111** [comment]
:+1:

**Comment by ItaipuTechnology** [comment]
:+1:

**Comment by metherton** [comment]
:+1:

**Comment by rafischer** [comment]
Search google for "git workflow best practices"

**Comment by cbrownrt** [comment]
:+1:

**Comment by BFCIV** [comment]
:+1:

**Comment by annavester** [comment]
:+1:

**Comment by jaw6** [comment]
@jcbustamante2015 & all: we're all fans of [GitHub Flow](https://guides.github.com/introduction/flow/) here -- open a branch, add commits, open a pull request, discuss, merge. You might find [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/) interesting -- I have seen some teams work well with it, but my experience is that it's all too often over-kill for _most_ teams.
