### ISSUE TITLE
difference between cloning and branching?

### ISSUE THREAD

**Issue by satishsaley** [githubteacher/github-for-developers-sept-2015#156]

**Comment by ericcurtin** [comment]
@satishsaley good question +1

**Comment by baxziila** [comment]
ditto - my company is cloning rather than branching off of already existing branches to jointly development in a branch. Is this practice ever recommended?

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by zeeshanSD** [comment]
:+1:

**Comment by brian-rickman** [comment]
:+1:

**Comment by ItaipuTechnology** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by jaw6** [comment]
@satishsaley: "Clone" means to copy the repository to your local work area (typically your laptop or development environment). "Branch" means to create a new human-friendly label (git calls it a "ref") where new commits will live, separated from, but sharing history with the main/current branch (typically `master`).

I'm imagining that you're really asking about "Fork" -- "Fork" is a GitHub technology that creates a new copy of a repository that's now owned by you. That is, if `userA` wants to work on `userB / repoB`, "Fork" creates a complete copy of the repository (as of now) under `userA / repoB`. The new repository would typically be added as a second remote in Git (eg, `git remote add fork https://url/here`). 

Forks are typically used when a developer wants to contribute to an open source project but isn't a collaborator of the open source project. In this case, the developer creates a Fork, adds commits to their fork, then sends a pull request from their fork back to the original, main project repository. In many cases, once the pull request has been merged into the main repository, the developer can then delete their fork (their copy of the main repository).

For teams that work together as a cohesive group, Fork adds often unnecessary overhead to development, but sometimes can serve as a sort of tiered permission system (repository collaborators are fully trusted with read & write privileges, less trusted team members work from a Fork and must send pull requests to the main repository, where they need to be reviewed/merged by the trusted team members).
