### ISSUE TITLE
Do watching a repo send emails for commits, merges, etc?

### ISSUE THREAD

**Issue by jmbalasalle** [githubteacher/github-for-developers-sept-2015#22]

**Comment by jmbalasalle** [comment]
:+1:

**Comment by jaw6** [comment]
@jmbalasalle "Watching" means that you receive notifications for new issues & pull requests. Whether you receive emails or web "pings" depends on your settings in https://github.com/settings/notifications

<img width="1003" alt="screen shot 2015-09-29 at 1 15 55 pm" src="https://cloud.githubusercontent.com/assets/2077/10173877/46ecca80-66ac-11e5-9da0-e5ff28ceba2e.png">

We don't have a setting that would send emails for every commit or merge. It should be straight-forward to set something like this up with our [Webhook API](https://developer.github.com/v3/repos/hooks/) but that's a bit outside the scope of our class this week.
