### ISSUE TITLE
How do I find all the people who are developing?

### ISSUE THREAD

**Issue by milindrao** [githubteacher/github-for-developers-sept-2015#329]
I see only 5 people in the @ mentions.  How would I be able to get a list of all the developers?  e.g. all the participants in this webinar.

**Comment by skchandon** [comment]
:+1:

**Comment by patrickmckenna** [comment]
@milindrao @skchandon The auto-populate list will always max out at five items. It's designed to be a convenience when typing, not an exhaustive list. You can see a list of all contributors to this repository by clicking on the icon noted below:

![contributors](https://cloud.githubusercontent.com/assets/3589536/10175974/dbc9f160-66a6-11e5-8ef9-31e4f766c564.png)
