### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by indijanc** [githubteacher/github-for-developers-sept-2015#331]
You'll probably touch this going forward, but I'll ask anway:

Could you merge changes on the master to your private branch and at a later point merge your changes back to master? Any issues there? Thanks.

**Comment by jaw6** [comment]
@indijanc we will cover merging, but: there's no problem with merging changes from `master` back into a development branch, or vice-versa. It's rare to see problems with this, but some developers will find it "messy". In practice, it's rarely a concern.
