### ISSUE TITLE
i cannot create a branch!!

### ISSUE THREAD

**Issue by sfeinholz** [githubteacher/github-for-developers-sept-2015#333]

**Comment by saranicole** [comment]
Click the Branch - master button then type a branch name and hit enter

**Comment by sfeinholz** [comment]
no option to create

**Comment by sfeinholz** [comment]
tried that, I only get an option to switch branches

**Comment by sfeinholz** [comment]
I am assuming I am a collaborator because I can open issues

**Comment by sbrinkmeyer** [comment]
@sfeinholz you need to comment on the issue #1 to become a collabortator? 

you are a colab if you can assign tags and stuffs

**Comment by sfeinholz** [comment]
i did comment; any way to check that I am a collaborator?
yes you are the collaborator now, you have a collaborator button :)
