### ISSUE TITLE
How many of GitHubs features can be accessed via command-line?

### ISSUE THREAD

**Issue by ericcurtin** [githubteacher/github-for-developers-sept-2015#337]
How many of GitHubs features can be accessed via command-line on Linux?

Us developers love the command line :)

Might be easier to say what you can't do via command-line.

**Comment by jaw6** [comment]
We'll cover the command line features of Git shortly. Almost everything in GitHub can be done via command line. We start with the browser to help focus on the social aspects of GitHub -- using issues and pull requests to collaborate. We'll move to the command line soon!
