### ISSUE TITLE
Check boxes in issues, etc.

### ISSUE THREAD

**Issue by cbrownrt** [githubteacher/github-for-developers-sept-2015#340]
Is there a way to restrict who can check a particular box, or track who checked it?

**Comment by jaw6** [comment]
@cbrownrt that's a good question: for better or worse, _any_ repository collaborator can check a checkbox in an issue. In a large, chaotic repository like ours today, that can sometimes be a bit of a problem, but, in my experience, it's rarely an issue in practice, as your team members aren't usually 100+ random developers in a webinar. :wink:

**Comment by cbrownrt** [comment]
So can you track who checked the box(es)?

**Comment by jaw6** [comment]
@cbrownrt not currently, but it's a commonly requested feature enhancement.
