### ISSUE TITLE
How to add new file and commit

### ISSUE THREAD

**Issue by ItaipuTechnology** [githubteacher/github-for-developers-sept-2015#343]
please get me going again on this. I had no access when you were demoing.tx

**Comment by saranicole** [comment]
Once you create a new branch, switch to the branch and you'll see a plus button next to the branch name.  Click the plus button and it will create a new file you can add text in.  You'll have to enter a file name at the top before you can commit it.

**Comment by ItaipuTechnology** [comment]
Found it.thanks!

**Comment by sbrinkmeyer** [comment]
@ItaipuTechnology can we close this issue?
