### ISSUE TITLE
Process for adding resources to the repository

### ISSUE THREAD

**Issue by kcentofante** [githubteacher/github-for-developers-sept-2015#348]
You have an awesome process for adding to the repository (commenting on Issue #1)
Is this something publicly available?
Thanks!
Kristin

**Comment by rtauber92054** [comment]
Hi Kristin

**Comment by kcentofante** [comment]
Hi @rtauber92054 !!

**Comment by jaw6** [comment]
@kcentofante @rtauber92054 -- thanks! in my experience, developers usually know their collaborating team members a little more formally than we do with students in our large webinars, but... in fact, _all_ of the materials we use in class are available as public, open source repositories, right here on GitHub: 
- Scripts are: https://github.com/github/training-utils
- Slides are: https://github.com/github/training-kit

Enjoy! (And send a pull request if you find any typos or bugs!)
