### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by ebremner17** [githubteacher/github-for-developers-sept-2015#353]
Still getting all the email notifications for the first comment and they are still coming in far too many.  Have the unwatch on.

**Comment by jaw6** [comment]
@ebremner17 you might want to unsubscribe from that thread - you can click the "Unsubscribe" button in https://github.com/githubteacher/github-for-developers-sept-2015/issues/1, on the right side, below "Labels"

![8 please comment here issue 1 githubteacher_github-for-developers-sept-2015](https://cloud.githubusercontent.com/assets/2077/10172183/9cab432e-66a3-11e5-8564-ab452ea189f0.jpg)
