### ISSUE TITLE
change file again after creating a pull request

### ISSUE THREAD

**Issue by lakshgupta** [githubteacher/github-for-developers-sept-2015#360]
is it possible to change the file again after creating a pull request; while in between the discussion.

**Comment by Ziliboba** [comment]
:trollface:

**Comment by hs186016** [comment]
:+1:

**Comment by sweetfisheric** [comment]
:monkey_face:

**Comment by jaw6** [comment]
@lakshgupta @Ziliboba @hs186016 @sweetfisheric -- short answer: yes, it is possible. :smile: When you add new commits to a branch, they will be included in any **open** pull requests associated with that branch. Once the pull request is closed (either successfully merged or abandoned), we stop associating new commits with that pull request.
