### ISSUE TITLE
How to do a command line pull request

### ISSUE THREAD

**Issue by abhibond** [githubteacher/github-for-developers-sept-2015#369]
How do we pull the code from the pull req branch, make changes and commit back to be discussed in the pull request?

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by heyword** [comment]
:+1:

**Comment by jaw6** [comment]
> How do we pull the code from the pull req branch

```
git pull
```

> make changes and commit back 

```
git add {files}
git commit -m "Commit message"
```

> to be discussed in the pull request?

```
git push
```
