### ISSUE TITLE
Can you set some sort of a deadline on pull requests?

### ISSUE THREAD

**Issue by ericcurtin** [githubteacher/github-for-developers-sept-2015#377]
Assuming you are using a model where you pull request has to be reviewed/signed-off by someone else. Is there a deadline you can set on a pull request so it doesn't stay in limbo forever?

**Comment by jaw6** [comment]
@ericcurtin it's not something we have built into GitHub, but it's not something I often see as a problem -- typically, developers are eager to get their changes into production. One workflow that seems to work well is to assign the pull request to the reviewer, who then uses the search/filter system to show open pull requests assigned to themselves to review. 

You could use our [Repository Webhooks](https://developer.github.com/v3/repos/hooks/) to set up a small service that tracks pull requests that haven't been reviewed in X days.
