### ISSUE TITLE
Can you enforce 2 person pull and commit

### ISSUE THREAD

**Issue by rtauber92054** [githubteacher/github-for-developers-sept-2015#379]
You mentioned that the person who creates pull request should not commit.
Can that be enforced in any way?

**Comment by rtauber92054** [comment]
Still waiting..

**Comment by brian-rickman** [comment]
:+1:

**Comment by heyword** [comment]
:+1:

**Comment by cbrownrt** [comment]
:+1:

**Comment by sreedasari** [comment]
:+1:

**Comment by OluOyedipe** [comment]
:+1:

**Comment by jaw6** [comment]
@rtauber92054 & others: we don't have a mechanism to enforce this social convention. We have a relatively new feature, called ["Protected Branches"](https://github.com/blog/2051-protected-branches-and-required-status-checks) which you can use to set specific test cases that _must_ be passing before a PR can be merged. You could combine this with something like Jenkins or [Travis CI](https://travis-ci.org/) to check a pull request's comments for a :+1: before marking the pull request as "passing".
