### ISSUE TITLE
Is there an official way to mark a PR as ready to merge?

### ISSUE THREAD

**Issue by schrags** [githubteacher/github-for-developers-sept-2015#383]
... or do you just signify the changes are ready based solely on the comments.

**Comment by tjcolvin** [comment]
:+1:

**Comment by jmatracia** [comment]
:+1:

**Comment by cbrownrt** [comment]
:+1:

**Comment by schrags** [comment]
:+1:

**Comment by jaw6** [comment]
@schrags & others: there's no convention that's :100:% for signaling "ready for review" across all of GitHub, but informally, we know that many projects use a label like `ready-for-review` to signal this. 

Informally, many developers prepend their pull request titles "WIP: Working on ..." when pull requests are still in progress, and use @mentions to alert reviewers when status changes.
