### ISSUE TITLE
Not able to merge. Closed with unmerged commits.

### ISSUE THREAD

**Issue by snigdhajain** [githubteacher/github-for-developers-sept-2015#390]

**Comment by snigdhajain** [comment]
#275

**Comment by jaw6** [comment]
@snigdhajain did you have a question about how to merge the pull request?

**Comment by snigdhajain** [comment]
Yes @jaw6 , when I clicked the Merge Pull request button, it said unable to merge. I tried a few times.

**Comment by jaw6** [comment]
@snigdhajain this can happen with large, active repositories, like this one (> 100 collaborators) -- as new pull requests get merged into `master`, we need to re-confirm that the pull request is safe to merge before enabling the big green merge button. Usually, reloading/re-trying the merge is enough, but, again, with _very_ active repositories, it can take a few tries. If you try again now, I expect you won't have any problems.

**Comment by Basis1977** [comment]
i am unbla to merge the close with unmerged commits
