### ISSUE TITLE
closing branch

### ISSUE THREAD

**Issue by indijanc** [githubteacher/github-for-developers-sept-2015#395]
How do I close my branch after I've merged it? I'm no longer on the pull request page.

**Comment by indijanc** [comment]
Sorry, that's delete, not close

**Comment by jaw6** [comment]
@indijanc looks like [this](https://github.com/githubteacher/github-for-developers-sept-2015/pull/219) is your pull request -- you should be able to click the `Delete Branch` button there.

**Comment by indijanc** [comment]
Thanks, just didn't find the pull request after it's been closed. Found it now.
