### ISSUE TITLE
Why delete a branch after merging?

### ISSUE THREAD

**Issue by gstanek** [githubteacher/github-for-developers-sept-2015#397]
What are the benefits/drawbacks?

**Comment by jaw6** [comment]
@gpstanek a branch is a lightweight, human-friendly label for a particular commit (eg, `abc123`). Once a pull request has merged, and that commit has been merged into the `master` branch, there's little value in preserving the human-friendly label pointing to `abc123`. The main drawback is _clutter_ -- the more branches remain open, the harder it is to spot actual work in progress in the repository.

**Comment by gstanek** [comment]
:+1:  thanks!
