### ISSUE TITLE
What happens when you revert a merge if subsequent merges have been made to master

### ISSUE THREAD

**Issue by milindrao** [githubteacher/github-for-developers-sept-2015#405]
Timeline 
 b1 -> master
 b2 -> master
 b3 -> master.
Now we find a mistake in b1, and want to revert it.  But b2 and b3 actually used the changes made in b1

**Comment by abhibond** [comment]
:+1:

**Comment by ap120266** [comment]
:+1:

**Comment by heyword** [comment]
:+1:

**Comment by sanjay990** [comment]
:+1:

**Comment by tjcolvin** [comment]
:+1:

**Comment by markowalsh** [comment]
:+1:

**Comment by cbrownrt** [comment]
:+1:

**Comment by schrags** [comment]
:+1:

**Comment by kukkadav** [comment]
+1

**Comment by kukkadav** [comment]
:+1:

**Comment by sreedasari** [comment]
:+1:

**Comment by BFCIV** [comment]
:+1:

**Comment by PavolC** [comment]
:+1:

**Comment by annavester** [comment]
:+1:

**Comment by jaw6** [comment]
@milindrao & all: Revert (either at the command-line, or the `Revert` button on GitHub Pull Requests) creates a new commit which does everything the opposite of the target commits/PR. Everything the target adds is subtracted and everything the target subtracts is added. 

When there are other/future commits/PRs in the repository, the effects of the Revert will depend on exactly what changes/changed in later commits/PRs -- it's possible the Revert has no conflicts with later PRs/commits (eg, they work on separate folders/files) but it's also possible for the Revert to introduce a merge conflict, in which case, say, the Revert PR wouldn't be automatically merge-able via the GitHub "green merge button".

We'll cover merge conflicts later in today's class -- the same solutions would apply to the Revert situation.
