### ISSUE TITLE
Branch Life in terms of Agile

### ISSUE THREAD

**Issue by jcbustamante2015** [githubteacher/github-for-developers-sept-2015#410]
Based on what you said, would you say it is a good practice to have a branch per user story in a sprint? Or would you expect to have a branch per release? Sounds like we should have a branch be as focused as possible and be based on changes in a story versus the changes in a release. Thoughts?

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by pdxtom** [comment]
:+1:

**Comment by sweetfisheric** [comment]
:+1:

**Comment by OluOyedipe** [comment]
:+1:

**Comment by cbrownrt** [comment]
:+1:

**Comment by BFCIV** [comment]
:+1:

**Comment by markowalsh** [comment]
:+1:

**Comment by abhibond** [comment]
:+1:

**Comment by cherrybee** [comment]
:+1:

**Comment by ericcurtin** [comment]
:+1:  Branch per user story in a sprint seems like a good rule of thumb to me or branch per feature.

**Comment by jaw6** [comment]
@jcbustamante2015 - great question! We typically recommend one branch per "discrete" action. A bug or user story is a good rule of thumb. There's almost zero cost to having branches in Git/GitHub -- so branch early + branch often is usually a good habit to be in. We do sometimes see cases where longer-lived or multiple-story branches makes sense (maybe imagine a big, high-point story {which probably really should have been broken up into multiple stories} with several deploy-test cycles), but as you might imagine, those are pretty rare in practice -- or at least, they _should_ be.
