### ISSUE TITLE
Incomplete revert branch request

### ISSUE THREAD

**Issue by vb186017** [githubteacher/github-for-developers-sept-2015#413]
![Screenshot](https://cloud.githubusercontent.com/assets/14892978/10173096/6688eb54-6697-11e5-9dce-bfefe92cdaf8.png)

**Comment by vb186017** [comment]
I clicked to revert my branch. Never created a pull request for the revert. What is the state of the revert pull request?

**Comment by jaw6** [comment]
@vb186017 good question! The state is: there is a branch open, with a commit that would be the opposite of any commits in pull request #325. In a "real" project (ie, not for class), your collaborators might wonder what's going on -- why not create a pull request? or delete the branch? But, for our class this week, no need to worry about it.

**Comment by vb186017** [comment]
I really didn't wanted to create a pull request. For this class I was testing on how to create a pull request but just wanted to check how revert worked. I was just planning to hit Cancel, but didn't see any option. Is there a way I can delete the open branch? I was not able to find an option for it.

**Comment by jaw6** [comment]
@vb186017 sure, visit the [branches tab](https://github.com/githubteacher/github-for-developers-sept-2015/branches), toggle to `Your Branches` and click the "trash" icon to delete the branch.

**Comment by vb186017** [comment]
Thanks a lot. This was helpful.
