### ISSUE TITLE
Demo Questions

### ISSUE THREAD

**Issue by ssackrider** [githubteacher/github-for-developers-sept-2015#419]
@rafischer @lisascullystein @dlinstruth @pkirby 
### demo questions
- Will we have to create a branch for EVERY task #?  or what will be our branch  
- How do we check in multiple files at once?

**Comment by rafischer** [comment]
@ssackrider message received.  You broke the build again.

**Comment by jmatracia** [comment]
@BHoward67 bump

**Comment by tjcolvin** [comment]
@ssackrider I believe you would create a new branch for every task. This would allow you to check in a branch without worrying about changes you may have made for another task.

Edit: At least as far as I know.

**Comment by jaw6** [comment]
> Will we have to create a branch for EVERY task #? or what will be our branch

Will typically recommend one branch per logical "unit" -- typically one branch per issue, story, feature or bug. There are cases where that doesn't follow (long features, several point stories that really _should_ have been broken down into smaller units, etc) but it's typically a useful workflow/strategy for most development workflows. Branches are lightweight references, there's very little downside to having multiple branches (perhaps visual clutter).

> How do we check in multiple files at once?

```
git add fileA
git add fileB
git commit -m "Commit fileA and fileB at once"
```
