### ISSUE TITLE
encourage people to : + 1 : on questions they are interested in

### ISSUE THREAD

**Issue by sbrinkmeyer** [githubteacher/github-for-developers-sept-2015#420]
this way we could sort by number of comments and get the higher rated questions answered

**Comment by githubteacher** [comment]
:+1:

**Comment by gdmalet** [comment]
+1

**Comment by aabognah** [comment]
:+1:

**Comment by chvrsi** [comment]
you're about to get a lot of :+1:

**Comment by kevinscully** [comment]
:+1:

**Comment by gdmalet** [comment]
:+1:  I mean.... heh

**Comment by ethanpwhite** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
