### ISSUE TITLE
File question

### ISSUE THREAD

**Issue by lisascullystein** [githubteacher/github-for-developers-sept-2015#421]
How do we check in multiple files at once for a branch?

**Comment by kaiyuan01** [comment]
test :+1:

**Comment by jaw6** [comment]
@lisascullystein @kaiyuan01 -- good question! With the "in browser editor", it's not possible -- we can only edit one file at a time. We'll switch focus to the command-line :soon:, where we'll be able to commit more than one file. I'll remind Patrick to make sure he demonstrates this on screen!
