### ISSUE TITLE
Best Practice on Migrating from other Version Control Systems or SW Baselines

### ISSUE THREAD

**Issue by ItaipuTechnology** [githubteacher/github-for-developers-sept-2015#425]

**Comment by ethanpwhite** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by patrickmckenna** [comment]
@ItaipuTechnology That depends heavily on what system you're migrating from, how much you want to transfer, and with what fidelity. I'd start by looking at our [GitHub Importer tool](https://import.github.com/new). If you have more specific questions, please let us know.
