### ISSUE TITLE
Is there a way to add a checklist template

### ISSUE THREAD

**Issue by OluOyedipe** [githubteacher/github-for-developers-sept-2015#429]
Looking for  an easy way to load a checklist into any PR

**Comment by BFCIV** [comment]
:+1:

**Comment by jaw6** [comment]
@OluOyedipe @BFCIV this isn't currently a feature of GitHub, but, as one option, you could add a `template.md` file to your repository and link to it from `CONTRIBUTING.md`. See [this document](https://github.com/blog/1184-contributing-guidelines) for more details on `CONTRIBUTING.md`.
