### ISSUE TITLE
Importance of version Labels

### ISSUE THREAD

**Issue by abhibond** [githubteacher/github-for-developers-sept-2015#431]
How are version labels used and what are the best practices?

**Comment by BFCIV** [comment]
:+1:

**Comment by jaw6** [comment]
@abhibond @BFCIV sorry, can you clarify - we've been using labels for Issues and Pull Requests, are those the labels you mean? I'm not sure about "version Labels" ?

**Comment by sbrinkmeyer** [comment]
actually yes, cause we can create ?tags? in that same branch pull down.  i'm curious about "labels" in svn or tags? in git? @jaw6

**Comment by jaw6** [comment]
@sbrinkmeyer sure, you can create a tag, just click the "Tags" tab in the branch pull down:

![githubteacher_github-for-developers-sept-2015](https://cloud.githubusercontent.com/assets/2077/10202066/bdec7c0c-6774-11e5-915e-6da5aa87faeb.jpg)

In Git, a tag is, like a branch, a human-friendly reference for a specific commit SHA. Unlike a branch, which will update to follow along with any new commits made while checked out to the branch, tags do not move. Tags are primarily used to indicate a "release" (or version) of the software in the repository.
