### ISSUE TITLE
If two people are working on a feature, should they branch the branch?

### ISSUE THREAD

**Issue by ericcurtin** [githubteacher/github-for-developers-sept-2015#435]
Self-explanatory.

**Comment by jaw6** [comment]
@ericcurtin it depends. In some cases, typically for smaller or more limited features, it makes sense to work in the same branch. Typically, though, especially for someone new to Git/GitHub, you might want to work in separate branches and merge changes into one branch before opening a pull request. In some cases, a developer will open a pull request _targeting_ another branch -- typically pull requests are requests to merge from `a_branch` to `master`, but a pull request can be creating targeting _any_ branch, not just `master`.
