### ISSUE TITLE
If the master branch gets updated while you are working on your own branch...

### ISSUE THREAD

**Issue by ericcurtin** [githubteacher/github-for-developers-sept-2015#438]
How can I update my branch to get the changes from the master?
What if I want to merge a file that has been changed in master with a file I have changed in my branch?

**Comment by sanjay990** [comment]
git checkout master
git pull
git checkout <branch>
git rebase master

**Comment by jaw6** [comment]
@sanjay990's answer should work most of the time. Keep in mind, though, that if your branch has been pushed, you'll want the last command to be `git merge master` instead of `git rebase master`. I'm hoping we'll have time tomorrow to talk about `rebase` in more depth.
