### ISSUE TITLE
trouble authenticating connection over https

### ISSUE THREAD

**Issue by ap120266** [githubteacher/github-for-developers-sept-2015#439]
it looks like my setup is wonky:

 git --version
git version 2.5.3
 git remote set-url origin https://github.com/githubteacher/github-for-developers-sept-2015.git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by jaw6** [comment]
@ap120266 in a corporate-managed network, you may need to switch to using `ssh` URLs, or configure an HTTPS proxy. Without knowing the details of your network (eg, your proxy configuration), I'd suggest trying the `ssh` URL first.

<img width="1041" alt="screen shot 2015-09-29 at 1 10 48 pm" src="https://cloud.githubusercontent.com/assets/2077/10173732/8f17da26-66ab-11e5-881c-215250fd8c58.png">

Click the blue `SSH` link to toggle to an `ssh` URL:

<img width="1019" alt="screen shot 2015-09-29 at 1 10 55 pm" src="https://cloud.githubusercontent.com/assets/2077/10173741/9a9ad75e-66ab-11e5-862e-73696ec37795.png">

Copy that URL and try that in your terminal:

```
git remote set-url origin git@github.com:githubteacher/github-for-developers-sept-2015.git
```

**Comment by ap120266** [comment]
@jaw6 Thanks for your help,

after adding the rsa.pub key to my account it seems to have worked:

git clone git@github.com:githubteacher/github-for-developers-sept-2015.git
Cloning into 'github-for-developers-sept-2015'...
remote: Counting objects: 1546, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1546 (delta 2), reused 0 (delta 0), pack-reused 1538
Receiving objects: 100% (1546/1546), 208.93 KiB | 141.00 KiB/s, done.
Resolving deltas: 100% (247/247), done.
Checking connectivity... done.
