### ISSUE TITLE
Does "git push" command if executed on some custom branch, by default does push for all branches including master?

### ISSUE THREAD

**Issue by Ziliboba** [githubteacher/github-for-developers-sept-2015#442]
Seems to be  dangerous  to be the default behavior?  Much more dangerous with -f
How can we prevent such behavior?

**Comment by lkmorlan** [comment]
You can do:
git push --all
This will push all local branches.

**Comment by jaw6** [comment]
We usually recommend folks set this configuration setting:

```
git config --global push.default current
```

This configures git to _only_ push the currently checked out branch. The defaults have changed a few times in various versions of Git, so the exact behavior you experience without configuring will depend on the exact Git version, operating system, etc.
