### ISSUE TITLE
Failed connect to github.com:443; No error

### ISSUE THREAD

**Issue by markowalsh** [githubteacher/github-for-developers-sept-2015#443]
fatal: unable to access 'https://github.com/githubteacher/github-for-developers-
sept-2015.git/': Failed connect to github.com:443; No error

**Comment by saranicole** [comment]
http://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github

**Comment by markowalsh** [comment]
Thanks @saranicole

**Comment by saranicole** [comment]
Sure thing - looks like others are having the same problem
