### ISSUE TITLE
how do I fix this clone error

### ISSUE THREAD

**Issue by CSAmador** [githubteacher/github-for-developers-sept-2015#445]
C:\Users\CA120453\Documents\GitHub> git clone https://github.com/githubteacher/g
ithub-for-developers-sept-2015.git
Cloning into 'github-for-developers-sept-2015'...
fatal: bad numeric config value 'inp' for 'core.autocrlf' in C:\Users\CA120453/.
gitconfig: invalid unit
C:\Users\CA120453\Documents\GitHub>

**Comment by CSAmador** [comment]
Also, I downloaded this for the everyone class; are there additional steps for this class?

**Comment by CSAmador** [comment]
C:\Users\CA120453\Documents\GitHub> git --version
git version 1.9.5.github.0
C:\Users\CA120453\Documents\GitHub>

**Comment by saranicole** [comment]
try:

git config --global core.autocrlf input

It looks like you incorrectly set it to "inp"

**Comment by CSAmador** [comment]
Thanks. that worked.

**Comment by mjahmed-wd** [comment]
> try:
> 
> git config --global core.autocrlf input
> 
> It looks like you incorrectly set it to "inp"

Thanks, that works for me

my bash also showed "fatal: bad boolean config value 'true~' for 'core.autocrlf'" error earlier

**Comment by charan-happy** [comment]
fatal: bad boolean config value 'truerecentrepo = C:/users/user' for 'core.logallrefupdates'
i am getting this error while initializing new repository.
please help me out with this issue

**Comment by RashidAli00** [comment]
fatal: bad boolean config value 'simple' for 'push.autosetupremote'
I am getting this error while the code is pushed on the repository.
please help me out with this issue
