### ISSUE TITLE
Can you branch a specific version in the master?

### ISSUE THREAD

**Issue by rajkumar79** [githubteacher/github-for-developers-sept-2015#450]

**Comment by Ziliboba** [comment]
:+1:

**Comment by lkmorlan** [comment]
You can do:

git checkout -b new-branch-name REF

That makes a new branch which will be the same as REF. REF can be the name of a branch, the name of a tag, or a commit hash such as "8ba9d67" (every commit is identified by a hash).

**Comment by jaw6** [comment]
@rajkumar79 @Ziliboba -- I'm not I understand the question, but I think you're asking if you can create a branch pointing at a specific point in time.

Typically, when we do:

```
git branch new_branch
```

We create a new branch, here called `new_branch` that's based on the currently checked-out branch, here, that'd be `master`.

If we want, we could create a new branch that was based on, just for example, [this commit](ff88dd51) when pull request 525 was merged in:

```
git branch after_525 ff88dd51
```

---

Does that answer the question?
