### ISSUE TITLE
Too fast on the command line

### ISSUE THREAD

**Issue by rtauber92054** [githubteacher/github-for-developers-sept-2015#452]

**Comment by rtauber92054** [comment]
start over please

**Comment by BFCIV** [comment]
:+1:

**Comment by maryfries** [comment]
:+1: I got lost right at the beginning because of the two readme versions...

**Comment by jdtao** [comment]
:+1:

**Comment by neicher1** [comment]
:+1:

**Comment by rajkumar79** [comment]
+1

**Comment by moliverio** [comment]
:+1:

**Comment by maryfries** [comment]
Are we supposed to be keeping up with the command line stuff on our own machines? He keeps clearing the screen. I'm totally lost. Can we watch this online somewhere?

**Comment by chvrsi** [comment]
I'll admit that I got lost pretty fast during the configuration part.  Manged to catch up though.

**Comment by maryfries** [comment]
He keeps clearing the screen after he types something.

**Comment by maryfries** [comment]
Can you please post the list of commands we should be entering to catch up?

**Comment by jaw6** [comment]
Hey folks: Sorry about the pacing in the last segment. We will post a video (typically takes a few hours to process) after tomorrow's class. If you'd like to review before tomorrow, here are links to the material we covered in today's class:
- [Basic Command Line Interface (CLI) Configuration](https://training.github.com/kit/modules/CONT-CLI-01_Basic-Configuration.html)
- [Cloning a Repository](https://training.github.com/kit/modules/CONT-CLI-02_Cloning-repository.html)
- [Editing Local Files](https://training.github.com/kit/modules/CONT-CLI-03_Editing-local-files.html)
- [The Two Stage Commit](https://training.github.com/kit/modules/CONT-CLI-04_Two_Stage_Commit.html)
- [Pushing Changes](https://training.github.com/kit/modules/CONT-CLI-05_Sync-changes.html)

/cc @patrickmckenna
