### ISSUE TITLE
in a bad way on the command line can't git pull on master

### ISSUE THREAD

**Issue by sbrinkmeyer** [githubteacher/github-for-developers-sept-2015#453]
Updating 5176ae8..601839f
error: Your local changes to the following files would be overwritten by merge:
    README.md
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by saranicole** [comment]
Do a git reset --hard then git pull

**Comment by jaw6** [comment]
@sbrinkmeyer the `git reset --hard` suggested by @saranicole _will_ work, but you'll lose anything you've typed locally. For today's class, it's probably nothing super important, but in your daily grind, this could be tragic. I'd suggest:

```
git stash
git pull
git stash pop
```

`git stash` will save local changes in a temporary state (it's sort of like a branch, but hidden from other branches) then `pull` in remote changes, then `stash pop` will put your local changes back where they were.

**Comment by saranicole** [comment]
@jaw6 good point thank you
