### ISSUE TITLE
unable to clone in the git bash

### ISSUE THREAD

**Issue by BFCIV** [githubteacher/github-for-developers-sept-2015#454]
BClardy@BCLARDY3 MINGW64 ~
$ git clone https://github.com/githubteacher/github-for-developers-sept-2015.gi
t
Cloning into 'github-for-developers-sept-2015'...
fatal: unable to access 'https://github.com/githubteacher/github-for-developers-
sept-2015.git/': Failed to connect to github.com port 443: Timed out

BClardy@BCLARDY3 MINGW64 ~

**Comment by jdtao** [comment]
:+1:

**Comment by saranicole** [comment]
Try:

ssh -T -p 443 git@ssh.github.com

https://help.github.com/articles/using-ssh-over-the-https-port

If that fails update the http.proxy key as doc'ed here:

http://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github

**Comment by jaw6** [comment]
@BFCIV let us know if @saranicole's solution doesn't work for some reason, but I expect that's what you need to do. (Thanks @saranicole!)
