### ISSUE TITLE
Difference between Gitlab and Github

### ISSUE THREAD

**Issue by jcbustamante2015** [githubteacher/github-for-developers-sept-2015#46]
When you get a chance, are you able to explain the differences between **github** and **gitlab**, and if they are just different products?

**Comment by nathanv** [comment]
I'm interested in this too.

**Comment by jcbustamante2015** [comment]
@githubteacher - your thoughts?

**Comment by ericcurtin** [comment]
Not the official answer from the teacher, but GitLab is an open-source project that basically copied GitHub and it's features. GitHub is closed source. Think of it this way GitHub is Unix (the original), GitLab is Linux (the open-source copy).

**Comment by jcbustamante2015** [comment]
@ericcurtin - thanks!

**Comment by metherton** [comment]
:+1:

**Comment by skchandon** [comment]
:+1:

**Comment by patrickmckenna** [comment]
@jcbustamante2015 The "official" answer is they're separate companies that offer similar products.
