### ISSUE TITLE
Problem with git push

### ISSUE THREAD

**Issue by ericcurtin** [githubteacher/github-for-developers-sept-2015#490]
~/git/github-for-developers-sept-2015>git push -u origin demo-local-branch-ericcurtin
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/githubteacher/github-for-developers-sept-2015.git/info/refs

fatal: HTTP request failed

I'm on git version 1.7.1. Unfortunately that's the latest version on my development environment, CentOS 6.7

**Comment by saranicole** [comment]
Are you getting a login prompt on the console?  You will need to configure an SSH key that authenticates to your github account.

https://help.github.com/articles/set-up-git/

https://help.github.com/articles/generating-ssh-keys/

**Comment by jaw6** [comment]
@ericcurtin First: 1.7.1 is _very_ old. It's disappointing that this is the most recent version in CentOS package repository. Please be aware, there was a _significant_ security issue discovered in Git [several months back](https://github.com/blog/1938-vulnerability-announced-update-your-git-clients) and we _strongly_ advise you to upgrade, even if you need to [compile git from source](https://www.howtoforge.com/how-to-install-the-latest-git-version-on-centos)

Second: There are several things that _could_ be happening. [This guide](https://help.github.com/articles/https-cloning-errors/) is a pretty thorough walk through to trouble-shooting this.

I'm going to close the issue for now to clear it from our screens, but please re-open if you need more help!
