### ISSUE TITLE
Please post result of "history | grep git" so we can catch up during break.

### ISSUE THREAD

**Issue by neicher1** [githubteacher/github-for-developers-sept-2015#491]

**Comment by nathanv** [comment]
Great idea :+1:

**Comment by patrickmckenna** [comment]
@neicher1 @nathanv My laptop actually froze after class, so I couldn't get this -- sorry! However, we're recording both days, and I'll try to get tomorrow CLI history saved as well. Also, we'll going over command line Git much more thoroughly tomorrow, including a reprise of everything we quickly covered today.
