### ISSUE TITLE
Aren't local branches supposed to inherit the upstream branch from a clone?  Got an error.

### ISSUE THREAD

**Issue by kevinman42** [githubteacher/github-for-developers-sept-2015#493]
fatal: The current branch krs-branch-2 has no upstream branch.
To push the current branch and set the remote as upstream, use

```
git push --set-upstream origin krs-branch-2
```

**Comment by kevinman42** [comment]
Ran the command "git push -u origin" while in my local branch context.

**Comment by jaw6** [comment]
@kevinman42 if you've cloned with the default options, then `master` is the only local branch I'd expect to be wired up to the upstream tracking `master` branch. When you create a new branch (eg, `krs-branch-2`), it won't be tracking any upstream branches until/unless you push with `-u` (or `git branch -u` to set this without pushing)
