### ISSUE TITLE
Getting failed to push some refs errors.

### ISSUE THREAD

**Issue by ghost** [githubteacher/github-for-developers-sept-2015#502]
error: src refspec demo-local-Andy-branch does not match any.
error: failed to push some refs to 'https://github.com/githubteacher/github-for-
developers-sept-2015.git'

**Comment by ghost** [comment]
When running the command "git push -u origin demo-local-andy-branch"

**Comment by saranicole** [comment]
Try:
git pull --rebase

As described here:
http://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to

**Comment by ghost** [comment]
Delete the repository, re-cloned from master, and then created a branch.
touched a file, and then committed.. git status indicates everything is clean and commited.

git status
On branch krestel-andy-local-branch
nothing to commit, working directory clean

then do a push.. make sure the name is the same as the branch.

ocal-branch]> git push -u origin krestel-andy-local-branch
Counting objects: 30, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (19/19), 2.26 KiB | 0 bytes/s, done.
Total 19 (delta 8), reused 14 (delta 4)
To https://github.com/githubteacher/github-for-developers-sept-2015.git
- [new branch]      krestel-andy-local-branch -> krestel-andy-local-branch
  Branch krestel-andy-local-branch set up to track remote branch krestel-andy-loca
  l-branch from origin.

**Comment by jaw6** [comment]
@krestel1 sounds like you got it working -- anything we can do to help here?

**Comment by ghost** [comment]
I am good, thanks. I am not sure if it was me typing everything. I think that error that you got in the beginning when you were cloning (regarding new files) and when you try to delete those files, threw everyone a curve ball, that was when I started falling behind.
