### ISSUE TITLE
error pushing

### ISSUE THREAD

**Issue by sfeinholz** [githubteacher/github-for-developers-sept-2015#510]
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by saranicole** [comment]
execute:
git pull

If that says "Aborting", execute:
git reset --hard

to remove local changes

**Comment by sfeinholz** [comment]
tried the pull; did not help; will try the reset

**Comment by saranicole** [comment]
@jaw6 recommends git stash so you can restore local changes instead of just deleting them

`git stash \
git pull \
git stash pop`
