### ISSUE TITLE
How to handle case sensitive and non-case sensitive file systems issues?

### ISSUE THREAD

**Issue by hbalagtas** [githubteacher/github-for-developers-sept-2015#516]
How to handle case sensitive and non-case sensitive file systems issues, we've had this issue with users on Windows and Mac. I think that was the issue when you pulled locally and already there were changes.

**Comment by jaw6** [comment]
@hbalagtas Unfortunately, there's only so much Git can do to work around non-case sensitive operating systems. If your repository, say, has `directoryA` and `Directorya`, Windows users will see all files from both directories presented locally under exactly one folder. Windows users can use `git mv FileA filea` to move (rename) a file with a wrong case name to a better name. If you often work across operating systems, the best is to ensure you don't create two files with different contents and similar-but-not-identical cases on Unix/Mac systems. (It's usually not that common.)

Note that this would be an issue with _any_ cross-platform system, it's not unique to Git/GitHub.
