### ISSUE TITLE
Need to re-clone the repository. How to delete the local repository?  

### ISSUE THREAD

**Issue by WeitiHuang** [githubteacher/github-for-developers-sept-2015#517]

**Comment by saranicole** [comment]
From the directory containing the folder:
rm -rf github-for-developers-sept-2015

**Comment by WeitiHuang** [comment]
Thanks!!

**Comment by maryfries** [comment]
I think I have one inside another. How do I clear them both?

**Comment by saranicole** [comment]
So long as you are in the directory above the parent, `rm -rf` to the parent will remove both parent and child directories

**Comment by nathanv** [comment]
Make sure you're in the right directory when you do it. Type `pwd` to see which directory you're in
