### ISSUE TITLE
Two githubs

### ISSUE THREAD

**Issue by cbrownrt** [githubteacher/github-for-developers-sept-2015#522]
I have an in-house github, plus yours at github.com.  When I do pushes, they are going to the in-house one.  How do I tell the push which one to go to?

**Comment by hbalagtas** [comment]
Look into git remote http://git-scm.com/docs/git-remote

Basically you can push you project to multiple repositories.

**Comment by milindrao** [comment]
My github email address is different from the enterprise email address.  I changed the global configuration.  I guess I need to figure out how to change the email address for the repository.  Not change the global email address

**Comment by milindrao** [comment]
:+1:

**Comment by patrickmckenna** [comment]
@cbrownrt Hopefully the answer provided during class cleared things up?

**Comment by cbrownrt** [comment]
Once I got my proxy straightened out, it worked perfectly.
