### ISSUE TITLE
git push error 403

### ISSUE THREAD

**Issue by ts122492** [githubteacher/github-for-developers-sept-2015#526]
1600 ~: $ git push --set-upstream origin woot
Username for 'https://github.com': ts122492
Password for 'https://ts122492@github.com': 
remote: Permission to githubteacher/github-for-developers-sept-2015.git denied to ts122492.
fatal: unable to access 'https://github.com/githubteacher/github-for-developers-sept-2015.git/': The requested URL returned error: 403

**Comment by saranicole** [comment]
Take a look at:

http://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github
