### ISSUE TITLE
Better quality audio tomorrow if possible.

### ISSUE THREAD

**Issue by bcmatz** [githubteacher/github-for-developers-sept-2015#533]
I can hear you, but not clearly many times.  There is a slight echo, and another line seems to be bleeding through periodically.

Not sure if this is something you have control over as you had mentioned things going on in your office that are not in your control, but thought I'd mention it.

**Comment by patrickmckenna** [comment]
@bcmatz Thanks for the info, I will see if there's a potentially quieter room available tomorrow.
