### ISSUE TITLE
Deleting branch locally vs remotely

### ISSUE THREAD

**Issue by WoodyTheWoodman** [githubteacher/github-for-developers-sept-2015#535]
How do you sync up the deletion of branches locally vs remotely? I can delete locally, but it still exists remotely and vice versa. Is there a better place to delete branches so that the branches are synced up locally and remotely?

**Comment by nathanv** [comment]
You can delete remote branches as shown here:
http://gitready.com/beginner/2009/02/02/push-and-delete-branches.html

**Comment by WoodyTheWoodman** [comment]
@nathanv I understand that much. But what I was getting at is I delete the branch on GitHub.com, but then I still have the local copy, which I also have to delete. So I'm wondering if there is any way of syncing branches on GitHub.com vs locally.

Additionally, if I delete the branch on GitHub.com, can I still make updates to my local branch and then push those changes? Or will GitHub barf because the GitHub.com version of the branch has already been deleted? Or will GitHub.com see it as a new branch?

**Comment by jaw6** [comment]
Git is designed to operate offline as much as possible -- local branches can be configured to "track" branches on a remote service (GitHub) but that "tracking" is really just setting a few sensible defaults for the `push` and `pull` commands -- essentially allowing you to type `git pull` without always having to explicitly say where you want to pull from/push to. 

For better or worse, this design means that you'll need to delete local branches manually if you delete them from the web interface. There are a variety of solutions online to scripting this behavior, if it's something you'd like to automate, try [starting here](http://stackoverflow.com/questions/6127328/how-can-i-delete-all-git-branches-which-have-been-merged)
