### ISSUE TITLE
Updating Git over GitHub install

### ISSUE THREAD

**Issue by cbrownrt** [githubteacher/github-for-developers-sept-2015#544]
Last week I ran the GitHub install on my Win7 box and got it all running.  During class, @patrickmckenna had us do a git version command and mine came up with 1.9.5.github.0.  The latest is 2.5.3.  What is the right way to update to that latest version?

**Comment by jaw6** [comment]
@cbrownrt best is to download the installer from http://git-scm.com/download/win and install it. That should have you all set with the newest version.

**Comment by cbrownrt** [comment]
:smiley:
