### ISSUE TITLE
You seemed to be using autocomplete on git commands and branch names on command line?

### ISSUE THREAD

**Issue by busreset** [githubteacher/github-for-developers-sept-2015#547]
You seemed to be using autocomplete on git commands and branch names on the command line when you were showing how to use git locally.  Were you using the following bash script to do so (found through google search)?

http://code-worrier.com/blog/autocomplete-git/

Or something similar?  The posting is from 2012 so it is a bit dated and I'm not sure if it's widely supported / stable or not.

Looks like a very useful tool.

**Comment by busreset** [comment]
Oh, I see it's part of the git install when using homebrew on OS X, located in `/usr/local/etc/bash_completion.d/git-completion.bash`.  I already had it and didn't know.

**Comment by sfeinholz** [comment]
can any terminal window support this functionality? 
Not just GIT related?
I am on Windows.

**Comment by sfeinholz** [comment]
I downloaded and was using GitBash.
Does that support auto-complete?

**Comment by patrickmckenna** [comment]
@sfeinholz Auto-completion is a property of your CLI setup, and is not inherently Git-related. Many different programs offer this, but that varies depending on the program in question, your shell env, &c. I'm not sure whether GitBash offers this by default; I assume that you tried and found tab-complete doing nothing?

**Comment by sfeinholz** [comment]
that is correct; tab-complete did not work and I looked in the options and did not see anything to enable that feature.

do you know of any type of app that will work on Windows that supports auto-complete?

**Comment by busreset** [comment]
If I have to touch windows, I use cygwin as my development environment.  Basically a GNU/Linux/Unix command line & X windows environment. With cygwin, you get bash (and git if you choose to install it), so auto-completion will certainly work there, including git completion if you set it up.  http://cygwin.net/

**Comment by sfeinholz** [comment]
Thank you!

**Comment by patrickmckenna** [comment]
Thanks for the info, @busreset!
