### ISSUE TITLE
Still getting emails

### ISSUE THREAD

**Issue by sfeinholz** [githubteacher/github-for-developers-sept-2015#551]
Even though I set my settings to Ignoring, I still get emails from other people in the class.

**Comment by jmarlena** [comment]
Are these emails from issues that you've commented on?

**Comment by jaw6** [comment]
@sfeinholz you might have encountered a bug -- Ignoring should really mean **no notifications**. Can you link to an example where you got a notification _after_ setting the repository to Ignore ? I can forward it to our developers.
