### ISSUE TITLE
you ask people to not commit to master.  Can't you set access so that we cant and only you can pull?

### ISSUE THREAD

**Issue by sbrinkmeyer** [githubteacher/github-for-developers-sept-2015#553]

**Comment by jaw6** [comment]
All repository collaborators can write (commit & push) to any branch. It's possible to set up ["protected branches"](https://github.com/blog/2051-protected-branches-and-required-status-checks) that prevent deleting and "force pushing" to one or more branches. 

If you're looking to set up "tiers" of access to repositories, you might look at having developers Fork the main repository -- so, the "trusted" team has write access to the upstream/parent repository, less trusted developers work from their personal or team Fork.
