### ISSUE TITLE
How to sync to latest Master?

### ISSUE THREAD

**Issue by snigdhajain** [githubteacher/github-for-developers-sept-2015#555]

**Comment by sweetfisheric** [comment]
git fetch --all
git reset --hard origin/master

**Comment by jaw6** [comment]
@sweetfisheric's suggestion will work, but keep in mind that you'll be throwing away any commits you made locally on `master` (which you shouldn't do, but it happens). You can also do: `git pull --rebase` to update and move _any_ local `master` commits to _after_ any remote commits.
