### ISSUE TITLE
When trying to switch to master, i get: "error: Your local changes to the following files would be overwritten by checkout: 	readme.md Please, commit your changes or stash them before you can switch branches. Aborting"

### ISSUE THREAD

**Issue by snigdhajain** [githubteacher/github-for-developers-sept-2015#557]

**Comment by saranicole** [comment]
Make sure you have done a git pull first:
`git pull`

If you have and you still have trouble you might have local uncommitted changes

To stash (preserves local changes WITHOUT committing them):
`git stash \ git pull \ git stash pop`

To reset (discards all local changes)
`git reset --hard`
