### ISSUE TITLE
What do you do after "git commit"?

### ISSUE THREAD

**Issue by maryfries** [githubteacher/github-for-developers-sept-2015#561]
I ended up in a terminal editor that I couldn't get out of...

Sorry, not a terminal user...

mfries-mbp:github-for-developers-sept-2015 mfries$ git commit

Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch mary-branch
# Changes to be committed:
# new file:   mary-demo.md
# 

~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
~  
-- INSERT --

**Comment by maryfries** [comment]
![image](https://cloud.githubusercontent.com/assets/6549787/10199606/83ec09e6-676f-11e5-8e91-d88523ac263e.png)

**Comment by maryfries** [comment]
I'm still stuck here... I can't make the commit.

**Comment by saranicole** [comment]
You can add the flag "-m" to add a commit message right from the commit.

git commit -m "My awesome comment"

Then do a push to your branch:

git push -u origin mybranch

**Comment by maryfries** [comment]
I got to here:

mfries-mbp:github-for-developers-sept-2015 mfries$ git push -u origin test-push
Username for 'https://github.com': maryfries
Password for 'https://maryfries@github.com': 
error: src refspec test-push does not match any.
error: failed to push some refs to 'https://github.com/githubteacher/github-for-developers-sept-2015.git'
mfries-mbp:github-for-developers-sept-2015 mfries$

**Comment by maryfries** [comment]
OK, I got a commit to go through, but there then when I pushed it still says there is nothing to push...

**Comment by maryfries** [comment]
mfries-mbp:github-for-developers-sept-2015 mfries$ git commit -m "my commit"
[mary-branch 945af64] my commit
 1 file changed, 3 insertions(+)
 create mode 100644 mary-demo.md
mfries-mbp:github-for-developers-sept-2015 mfries$ git push -u origin test-push
error: src refspec test-push does not match any.
error: failed to push some refs to 'https://github.com/githubteacher/github-for-developers-sept-2015.git'
mfries-mbp:github-for-developers-sept-2015 mfries$ git status
On branch mary-branch
nothing to commit, working directory clean
mfries-mbp:github-for-developers-sept-2015 mfries$

**Comment by saranicole** [comment]
If you added a file you will also need to use `git add` to add it.

If you do `git status` it will tell you if there are any files that need to be added.

To add all files you can do `git add -A`

Then when you do your commit it should show up

What do you get when you do `git status` ?

**Comment by maryfries** [comment]
On branch mary-branch
nothing to commit, working directory clean

**Comment by maryfries** [comment]
i never got a pull request though...

**Comment by saranicole** [comment]
Try resetting your branch and add a file again:

git reset --hard

Then create a file:
touch myfile.txt

Add it:
git add myfile.txt

Commit:
git commit -m "My awesome file"

Push:
git push -u origin mary-branch

**Comment by saranicole** [comment]
You only do the pull request when you're trying to merge your branch into master, so that won't affect you right now.

`git pull` is for when someone else made a change that you're bringing into your local working directory

**Comment by saranicole** [comment]
Sounds like you're all set so I'm going to close this out.  Please reopen if not.

**Comment by maryfries** [comment]
Thanks SaraNicole!

**Comment by saranicole** [comment]
@maryfries Sure thing!
