### ISSUE TITLE
i want to clone from github, but then push to github.local.io how do?  

### ISSUE THREAD

**Issue by sbrinkmeyer** [githubteacher/github-for-developers-sept-2015#563]
is it just changing the origin  parameter?

**Comment by sbrinkmeyer** [comment]
@saranicole do you know?

**Comment by saranicole** [comment]
You need to add the other url as a remote.

git remote add <<nickname>> github.local.io

Then you can specify that with the -u parameter

https://help.github.com/articles/adding-a-remote/

**Comment by saranicole** [comment]
Like `git remote add myremote github.local.io`

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by saranicole** [comment]
Looks like this worked for you - closing out issue.
