### ISSUE TITLE
Is there a way to disable the "Markdown" support at the comment basis?

### ISSUE THREAD

**Issue by WeitiHuang** [githubteacher/github-for-developers-sept-2015#642]

**Comment by jaw6** [comment]
@1walterh all comments on GitHub are treated as Markdown. If you want to type something without it being rendered (say, a snippet of html code) you can surround that code with `(a backwards apostrophe, or "back-tick"; typically the key left of the 1 key, top left on a US keyboard). If you have more than one line, surround those lines with``` (three back-ticks).

**Comment by WeitiHuang** [comment]
@jaw Thanks. 

Can you give short examples?

**Comment by jaw6** [comment]
`this text is a one-line code sample`

and

```
this text
is a code sample
covering more
than one line
```

Click the "pencil icon" on this comment to see the formatting.
