### ISSUE TITLE
How does one solve "This branch has conflicts that must be resolved" in git while merging pull request?

### ISSUE THREAD

**Issue by jns111** [githubteacher/github-for-developers-sept-2015#648]

**Comment by jaw6** [comment]
You'll need to update your branch with new commits from master, resolve those conflicts and push the updated/resolved branch to GitHub. Something like this:

```
git checkout master
git pull
git checkout <branch>
git merge master
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push
```

**Comment by shankar26** [comment]
👍 , it helped me

**Comment by leonardojulius** [comment]
@jaw6 thanks it helps me :+1:

**Comment by kirankakkeratd** [comment]
@jaw6 perfect solution :100: . Thanks :+1:

**Comment by jitendravyas** [comment]
It helped me. thanks

**Comment by 23ranjan** [comment]
Perfect. Thanks.

**Comment by jitendravyas** [comment]
i get this error

`This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
`

**Comment by otisidev** [comment]
every helpful, thank you!

**Comment by nj1306** [comment]
If someone getting below error like me

> **fatal: cannot do a partial commit during a merge.**

use `-i` or `--include` flag with the `commit` command

`git commit -i -m "Your commit message"`

**Comment by Georodent** [comment]
What do you do in the ----resolve conflicts-----  part?   Also, will this work with a "conflicting file" as well?

**Comment by tdk408** [comment]
On "git checkout <branch>", should it be a new branch created for fixing the conflicts, or the original branch that reported the conflicts?

**Comment by ningcui-refundlabs** [comment]
perfect solution. Thanks.

**Comment by sunset12321215** [comment]
You are in the middle of a merge -- cannot amend.
help me please@@

**Comment by ghost** [comment]
Thanks

**Comment by veasnama** [comment]
thank sir that really works for me. i never thought i would be fine. this is my day.

**Comment by Ahkshaey** [comment]
@thanks. Worked like pure magic. Bookmarking it as a great resource when trying to resolve conflicts on git for future reference....

**Comment by hyungtaecf** [comment]
I got this after trying to merge with master:
Automatic merge failed; fix conflicts and then commit the result.

**Comment by lfc-256** [comment]
thanks @jaw6!

**Comment by repl-mohit-kumar** [comment]
the conflict occurred because after ur change, someone else updated that file
so Github could not determine which lines to keep and which to remove with ur change
when we merged master, we pointed the local HEAD to the master code and with that Github was able to fix the merge conflict automatically.

**Comment by OmarAlareeki** [comment]
Thank you, this is very helpful

**Comment by Carlo8699** [comment]
nice

**Comment by kazyon** [comment]
what if this error shows at a fork of a repo ?

**Comment by Wenjie76** [comment]
Thank you, quite helpful

**Comment by iLakshya** [comment]
Got the error. Thanks a ton ✌🏻

**Comment by sachelsout** [comment]
> You'll need to update your branch with new commits from master, resolve those conflicts and push the updated/resolved branch to GitHub. Something like this:
> 
> ```
> git checkout master
> git pull
> git checkout <branch>
> git merge master
> [ ... resolve any conflicts ... ]
> git add [files that were conflicted]
> git commit
> git push
> ```

Thank you so much !!!

**Comment by jimka2001** [comment]
I'm having trouble understand what to do here.
I have received a PR which github there contains a conflict.
I'd like to resolve the conflict.
The message https://github.com/githubteacher/github-for-developers-sept-2015/issues/648#issuecomment-144488223
suggests that I checkout some branch and resolve conflict.  BUT WHICH BRANCH? 
I do not see any branch which contains the conflicting commits.

What do I need to do get get a file containing the <<<<< ====== >>>>> conflict markers so I can fix them manually?

<img width="552" alt="Screenshot 2023-06-10 at 08 17 52" src="https://github.com/githubteacher/github-for-developers-sept-2015/assets/6414129/2da3aa44-3d38-41c3-88b9-bbb7a0934356">

**Comment by Avedena** [comment]
Hi there,

but how I get the conflicts shown? I do the steps under  "Use command line to resolve conflicts before continuing. " but nothing happens in the repro.

https://github.com/Avedena/StyleGAN-Human/pull/1
`git checkout -b stylegan-human-main main`
`git pull https://github.com/stylegan-human/StyleGAN-Human.git main`
`git checkout main`
`git merge --no-ff stylegan-human-main`
`git push origin main`

Thanks
