### ISSUE TITLE
SO I deleted branch through WEB but still on my local..?

### ISSUE THREAD

**Issue by rtauber92054** [githubteacher/github-for-developers-sept-2015#659]

**Comment by stevendluke** [comment]
:+1:

**Comment by rtauber92054** [comment]
tauber@SDGL11b17b849:~/git/github-for-developers-sept-2015

> git branch
>   ght-rtauber92054-update
> - master
>   rtauber@SDGL11b17b849:~/git/github-for-developers-sept-2015

**Comment by rtauber92054** [comment]
don't leave us hanging...

**Comment by jaw6** [comment]
That's right -- the local and remote (GitHub) branches are linked, but it's a loose connection, deleting the branch on GitHub doesn't _automatically_ delete your local branch.

Try `git branch -d <branch name>` to delete a branch that has already been merged. 

`git branch -D <name>` will override the safeguards and delete a branch that hasn't been merged.
