### ISSUE TITLE
after merge, how do i delete branch?

### ISSUE THREAD

**Issue by sfeinholz** [githubteacher/github-for-developers-sept-2015#664]

**Comment by saranicole** [comment]
Using command line:

git branch -d mybranch

From the ui - once you do the merge, it will show a button "Delete branch"

**Comment by sfeinholz** [comment]
ah, I thought patrick did it with the GUI and missed that step.

**Comment by saranicole** [comment]
Cool, thanks for confirming.  Will close out issue
