### ISSUE TITLE
git pull --rebase vs git merge 

### ISSUE THREAD

**Issue by metherton** [githubteacher/github-for-developers-sept-2015#677]

**Comment by saranicole** [comment]
:+1:

**Comment by PinoEire** [comment]
In short, merge is non-destructive while rebase rewrites the very history, resulting in a cleaner and more linear project. Using rebase in conjunction with pull behaves like moving any local change on the current master HEAD.

**Comment by cbrownrt** [comment]
:+1:

**Comment by saranicole** [comment]
How does the history get rewritten?  Does it erase the record of a particular commit?

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by PinoEire** [comment]
@saranicole Not quick to explain, better look at http://git-scm.com/docs/git-rebase :smile:

**Comment by saranicole** [comment]
@PinoEire cool, thank you

**Comment by jaw6** [comment]
> How does the history get rewritten? Does it erase the record of a particular commit?

This is a deep topic, but I'll try to explain here (in case we don't have time to cover it in depth during class). Git commits contain a pointer to the commit's parent (or, in the case of merge commits, parent**s**). A branch is a pointer to the latest commit in a chain of commits pointing backwards in "time". `rebase` (and other commands that alter history, like `reset`) change history by altering the parent-commit pointer(s) and updating the branch pointer to point to the new parent-pointing commits.

There's a good explanation of this [here](http://git-scm.com/book/en/v2/Git-Branching-Rebasing) and a visual in our (old) [slide deck](https://training.github.com/kit/advanced/#rewriting-and-crafting-history).
