### ISSUE TITLE
Why did the commands you used for resolving conflicts differ from github directions?

### ISSUE THREAD

**Issue by ringhilterra** [githubteacher/github-for-developers-sept-2015#681]
![githubcommandline](https://cloud.githubusercontent.com/assets/3506706/10200213/e57cdc1e-6759-11e5-8f26-49d7387a340b.PNG)

**Comment by uclabruins89** [comment]
+1

**Comment by jaw6** [comment]
The instructions GitHub provides for resolving a conflicted pull request will update the requesting branch with any changes from `master` (and, if you continue with Step 2, push the resolved merge directly into `origin/master`, resolving the pull request as a side-effect). In class, we're illustrating resolving a conflicted merge, a Git-level (not GitHub-level) operation that's likely to come up more often in day-to-day software development workflows.
