### ISSUE TITLE
While trying to merge, I get: "error: Your local changes to the following files would be overwritten by merge: 	Another file 	readme.md Please, commit your changes or stash them before you can merge. Aborting"

### ISSUE THREAD

**Issue by snigdhajain** [githubteacher/github-for-developers-sept-2015#682]
How to force overwriting of local changes in this case?

**Comment by Ziliboba** [comment]
Seems that you have uncommited changes on your current branch. Do git commit -m "commit message", and then try to merge again.

**Comment by NickGe** [comment]
:+1:

**Comment by saranicole** [comment]
Make sure you have done a git pull first:
`git pull`

If you have and you still have trouble you might have local uncommitted changes as @Ziliboba mentioned.

To stash (preserves local changes WITHOUT committing them):
`git stash \ git pull \ git stash pop`

To reset (discards all local changes)
`git reset --hard`

**Comment by mkaleem4** [comment]
where am i entering these commands??

**Comment by jamalfrnk** [comment]
git bash

**Comment by hualongfeng** [comment]
I also see this error, but my branch clean, that is, it has be commit. How do I solve it.

**Comment by himanshu4git** [comment]
Faced same issue but my reason was quite different. I setup git on windows powershell few days ago . later i switched to cygwin and was doing git pull. :) switching back to windows powershell resolved the issue.

**Comment by kirbyfern** [comment]
@mkaleem4 on the terminal on your current local branch in your current project folder

**Comment by sslsolutions** [comment]
i want to keep the changes in my local branch
