### ISSUE TITLE
what is the difference between origin master and orgin/master

### ISSUE THREAD

**Issue by bcmatz** [githubteacher/github-for-developers-sept-2015#687]
Different syntax, different operation ?

**Comment by bcmatz** [comment]
:+1:

**Comment by jaw6** [comment]
`origin` is the name of the remote -- it's a default, used by git when initially cloning. When manually adding a remote, you must give it a name, if there's _only_ one remote, it's traditional for developers to call it "origin" as well.

`master` is the name of a branch -- also a default, used by git when initially creating a new repository. Developers often use `master` as the name of the main, "production-ready" branch. `master` is name of the branch, used alone it usually means "the local branch, here on this :computer:" `origin/master` means "the remote branch, what's currently on :octocat:".

`origin master` (with a space) is separately specifying the remote and the branch name -- this is used in commands like `git push` -- `git push origin master` means: "push the local branch `master` to a branch also named `master` on the remote named `origin`"
