### ISSUE TITLE
Wouldn't it be easier to 'merge origin/master' to github teacher branch and update the pull request instead of the other way around?

### ISSUE THREAD

**Issue by jamie-cyber1** [githubteacher/github-for-developers-sept-2015#691]

**Comment by Ziliboba** [comment]
:+1:

**Comment by sbrinkmeyer** [comment]
:+1:

**Comment by jmarlena** [comment]
:+1:

**Comment by jaw6** [comment]
Either direction works. We would usually recommend merging `origin/master` into `feature` (and that's what's recommended elsewhere) but in class, we wanted to illustrate a few other things in one go (including closing a pull request as a side effect of pushing changes into master).
