### ISSUE TITLE
in github issues, can you mark an issue a duplicate of another issues?

### ISSUE THREAD

**Issue by sbrinkmeyer** [githubteacher/github-for-developers-sept-2015#705]
@saranicole are you with github?  or just another user?

**Comment by saranicole** [comment]
@sbrinkmeyer I'm another monkey like you

**Comment by saranicole** [comment]
@sbrinkmeyer some of these questions I know some I don't

**Comment by jaw6** [comment]
You can -- some projects even set up a `duplicate` label to make this easier.

**Comment by thorade** [comment]
There seems to be something automatic, too, see:
this issue is a duplicate of #1

**Comment by 5chdn** [comment]
@thorade this is super cool. how did you manage to add an alt text to the "duplicate of" words?

**Comment by thorade** [comment]
I did not do it, github did it
https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates

**Comment by bsonntag** [comment]
How can I unmark an issue marked as a duplicate?

**Comment by thorade** [comment]
@bsonntag 
https://help.github.com/articles/about-duplicate-issues-and-pull-requests/#unmarking-duplicates

**Comment by TomashKhamlai** [comment]
#1

**Comment by TomashKhamlai** [comment]
dubl #1

**Comment by TomashKhamlai** [comment]
this issue is a duplicate of #1

**Comment by TomashKhamlai** [comment]
#59 [woodoo](https://www.google.com)

**Comment by thorade** [comment]
Thanks for reaching out to GitHub Support!

We haven't reverted this feature, but we have made some changes to it based on feedback from users.

This should still work if you make a comment with only the phrase and the issue it relates to, and no other punctuation or text.

For example:

This will work - Duplicate of #1
This will not work - Duplicate of #1.
This will not work - Duplicate of #1. Please close this issue

I hope this helps to clarify.

Cheers,
John
GitHub Support

**Comment by thorade** [comment]
Duplicate of #1

**Comment by bsonntag** [comment]
@thorade does that apply to the "closes" feature too?

**Comment by thorade** [comment]
When closing issues from a pull request, you can have additional text and it will still close the issue.
