### ISSUE TITLE
Shortcut for entering git commit sha hash

### ISSUE THREAD

**Issue by saranicole** [githubteacher/github-for-developers-sept-2015#711]
It looks like Patrick is copying the sha hash for a commit over to the next line.  I see there is a way to specify a commit using shorthands ( http://superuser.com/questions/464716/when-checkout-a-previous-commit-is-there-a-quick-way-to-input-the-log-commit-ha ).

Is there a way to autocomplete the sha hash itself ( rather than use the shorthand ) ?

**Comment by jaw6** [comment]
I'm sure it's possible, but the specifics would vary a bit depending on shell, operating system, etc. One thing to keep in mind, is that you only need the minimum number of characters to uniquely identify the SHA in your repository. In small repositories, three characters is sometimes specific enough -- when it isn't, git will indicate that the SHA was "ambiguous". I typically use 5-8 characters (this scales up to several thousand commits).

**Comment by saranicole** [comment]
@jaw6 Okey doke - thanks!
