### ISSUE TITLE
branch name in command prompt?

### ISSUE THREAD

**Issue by ap120266** [githubteacher/github-for-developers-sept-2015#724]
this seems like it would be very useful

**Comment by jaw6** [comment]
The exact details will vary based on your operating system and shell, but if you're using Bash (most common shell), [these instructions](http://stackoverflow.com/questions/15883416/adding-git-branch-on-the-bash-command-prompt) should work.

**Comment by ap120266** [comment]
@jaw6  Thanks, am using bash, i'll give that a try.

Nice Job to both of you
